import type { AggregatorBatch } from './types'

export const mockIncomingBatches: AggregatorBatch[] = [
  {
    id: 'batch-1',
    batchIdentifier: '#BT - 98442',
    farmerName: 'Marcus Chen',
    farmerCode: 'F - 006',
    location: 'Takoradi, GHA',
    harvestedAt: '2025-04-13',
    quantityKg: 250,
    fieldAgentName: 'Sunday Abel',
    verificationStatus: 'verified',
    estimatedInspectionMins: 45,
    goodsType: 'Maize',
  },
  {
    id: 'batch-2',
    batchIdentifier: '#BT - 98443',
    farmerName: 'Sarah Rogers',
    farmerCode: 'F - 004',
    location: 'Soubre, CV',
    harvestedAt: '2025-04-13',
    quantityKg: 250,
    fieldAgentName: 'Tunde Aina',
    verificationStatus: 'pending',
    estimatedInspectionMins: 35,
    goodsType: 'Maize',
  },
  {
    id: 'batch-3',
    batchIdentifier: '#BT - 98444',
    farmerName: 'Alex Jenkins',
    farmerCode: 'F - 002',
    location: 'Kumasi, GHA',
    harvestedAt: '2025-04-13',
    quantityKg: 250,
    fieldAgentName: 'Tunde Aina',
    verificationStatus: 'pending',
    estimatedInspectionMins: 40,
    goodsType: 'Maize',
  },
  {
    id: 'batch-4',
    batchIdentifier: '#BT - 98445',
    farmerName: 'Sarah Rogers',
    farmerCode: 'F - 008',
    location: 'Kumasi, GHA',
    harvestedAt: '2025-04-13',
    quantityKg: 250,
    fieldAgentName: 'Sunday Abel',
    verificationStatus: 'flagged',
    estimatedInspectionMins: 55,
    goodsType: 'Maize',
  },
  {
    id: 'batch-5',
    batchIdentifier: '#BT - 98446',
    farmerName: 'Sarah Rogers',
    farmerCode: 'F - 007',
    location: 'Kumasi, GHA',
    harvestedAt: '2025-04-13',
    quantityKg: 250,
    fieldAgentName: 'Sunday Abel',
    verificationStatus: 'rejected',
    estimatedInspectionMins: 30,
    goodsType: 'Maize',
  },
]
