import * as React from 'react'
import { 
  LayoutDashboard, Home, Package, Users, Sprout, FileText, 
  ClipboardList, Award, FileBadge, Eye, Receipt, Banknote, 
  BarChart3, ShieldCheck, Send, Truck, Archive, Settings, 
  Scan, Map, CheckCircle, Layers, Plus, Box, Beaker, 
  MapPin, Activity, Maximize, Link, AlertTriangle, Calendar,
  Scale, FileEdit, GitBranch, Database, Clipboard, File, 
  ScrollText, FilePlus, Search, Inbox, History
} from 'lucide-react'

export const IconMap: Record<string, React.ReactNode> = {
  'layout-dashboard': <LayoutDashboard className='size-4' />,
  'home': <Home className='size-4' />,
  'package': <Package className='size-4' />,
  'users': <Users className='size-4' />,
  'sprout': <Sprout className='size-4' />,
  'file-text': <FileText className='size-4' />,
  'clipboard-list': <ClipboardList className='size-4' />,
  'award': <Award className='size-4' />,
  'file-badge': <FileBadge className='size-4' />,
  'eye': <Eye className='size-4' />,
  'receipt': <Receipt className='size-4' />,
  'banknote': <Banknote className='size-4' />,
  'bar-chart-3': <BarChart3 className='size-4' />,
  'shield-check': <ShieldCheck className='size-4' />,
  'send': <Send className='size-4' />,
  'truck': <Truck className='size-4' />,
  'archive': <Archive className='size-4' />,
  'settings': <Settings className='size-4' />,
  'scan': <Scan className='size-4' />,
  'map': <Map className='size-4' />,
  'check-circle': <CheckCircle className='size-4' />,
  'layers': <Layers className='size-4' />,
  'plus': <Plus className='size-4' />,
  'box': <Box className='size-4' />,
  'jar': <Beaker className='size-4' />,
  'map-pin': <MapPin className='size-4' />,
  'activity': <Activity className='size-4' />,
  'maximize': <Maximize className='size-4' />,
  'link': <Link className='size-4' />,
  'alert-triangle': <AlertTriangle className='size-4' />,
  'calendar': <Calendar className='size-4' />,
  'users-2': <Users className='size-4' />,
  'scale': <Scale className='size-4' />,
  'file-edit': <FileEdit className='size-4' />,
  'git-branch': <GitBranch className='size-4' />,
  'database': <Database className='size-4' />,
  'clipboard': <Clipboard className='size-4' />,
  'file': <File className='size-4' />,
  'scroll': <ScrollText className='size-4' />,
  'file-plus': <FilePlus className='size-4' />,
  'search': <Search className='size-4' />,
  'inbox': <Inbox className="size-4" />,
  'history': <History className="size-4" />
}
