export const currentUser = {
  name: 'Agrolinking Administrator',
  email: 'admin@agrolinking.com',
  initials: 'AA',
  role: 'cooperative',
}

export const sidebarNavigation = [
  {
    title: 'Platform',
    items: [
      {
        id: 'dashboard',
        label: 'Dashboard Overview',
        href: '/cooperative',
        icon: 'layout-dashboard',
      },
      {
        id: 'farmers',
        label: 'Farmers',
        href: '/cooperative/farmers',
        icon: 'users',
      },
      { id: 'farms', label: 'Farms', href: '/cooperative/farms', icon: 'map' },
      // { id: 'apiaries', label: 'Apiaries', href: '/cooperative/apiaries', icon: 'hexagon' },
      {
        id: 'products',
        label: 'Products',
        href: '/cooperative/products',
        icon: 'package',
      },
      {
        id: 'inventory',
        label: 'Inventory',
        href: '/cooperative/inventory',
        icon: 'package',
      },
      {
        id: 'personnel',
        label: 'Personnel',
        href: '/cooperative/personnel',
        icon: 'users',
      },
    ],
  },
  {
    title: 'Operations',
    items: [
      {
        id: 'start-crop',
        label: 'Start Crop Cycle',
        href: '/cooperative/operations/start',
        icon: 'sprout',
      },
      {
        id: 'record-op',
        label: 'Record Operation',
        href: '/cooperative/operations/record',
        icon: 'file-text',
      },
      // { id: 'honey-batches', label: 'Raw Honey Batches', href: '/cooperative/operations/honey', icon: 'archive' },
    ],
  },
  {
    title: 'Certification',
    items: [
      {
        id: 'cert-product',
        label: 'Upload Product Certification',
        href: '/cooperative/certifications/product',
        icon: 'award',
      },
      {
        id: 'cert-farm',
        label: 'Upload Farm Certification',
        href: '/cooperative/certifications/farm',
        icon: 'file-badge',
      },
      // {
      //   id: 'cert-ready',
      //   label: 'Certification Readiness',
      //   href: '/cooperative/certifications/readiness',
      //   icon: 'check-circle',
      // },
      {
        id: 'cert-view',
        label: 'View Certifications',
        href: '/cooperative/certifications',
        icon: 'eye',
      },
    ],
  },
  {
    title: 'Finance',
    items: [
      {
        id: 'finance-purchase',
        label: 'Record Purchase',
        href: '/cooperative/finance/purchase',
        icon: 'dollar-sign',
      },
      {
        id: 'finance-receivables',
        label: 'Receivables',
        href: '/cooperative/finance/receivables',
        icon: 'credit-card',
      },
    ],
  },
  {
    title: 'Reports',
    items: [
      {
        id: 'reports-analytics',
        label: 'Reports & Analytics',
        href: '/cooperative/reports',
        icon: 'bar-chart-3',
      },
      {
        id: 'compliance-analysis',
        label: 'Compliance Analysis',
        href: '/cooperative/compliance',
        icon: 'shield-check',
      },
    ],
  },
]

export const cooperativeDashboardStats = {
  totalMembers: 2,
  totalFarms: 7,
  totalArea: 2963.6,
  trackedProducts: 7,
  totalHarvests: 9,
}

export const farmPerformanceSummary = [
  {
    id: 'BATCH-22440715-1763994368948',
    product: 'Rice',
    farmName: 'Baba Beji Farms',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0016,
    compliance: 'Medium',
  },
  {
    id: 'BATCH-22440715-1764306013258',
    product: 'Rice',
    farmName: 'Baba Beji Farms',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0016,
    compliance: 'Medium',
  },
  {
    id: 'BATCH-22440715-1764603213504',
    product: 'Rice',
    farmName: 'Baba Beji Farms',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0016,
    compliance: 'Medium',
  },
  {
    id: 'BATCH-1768228411241',
    product: 'Ginger',
    farmName: 'BABA FARM',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0,
    compliance: 'Medium',
  },
  {
    id: 'BATCH-1738013823058',
    product: 'Sesame',
    farmName: 'Baba Beji Farms',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.00196,
    compliance: 'Medium',
  },
  {
    id: 'BATCH-1738812685837',
    product: 'Maize',
    farmName: 'Olamide Farms',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0,
    compliance: 'Medium',
  },
  {
    id: 'BATCH-1738832271815',
    product: 'Maize',
    farmName: 'Olamide Farms',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0,
    compliance: 'Medium',
  },
  {
    id: 'POTATO-2026-001',
    product: 'Organic Sweet Potato',
    farmName: 'N/A',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0,
    compliance: 'Medium',
  },
  {
    id: 'CASSAVA-2026-001',
    product: 'Heritage Cassava',
    farmName: 'N/A',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0,
    compliance: 'Medium',
  },
  {
    id: 'MAIZE-2026-001',
    product: 'Premium Vitamin A Maize',
    farmName: 'N/A',
    farmer: 'Olamide Olutekunbi',
    status: 'planting',
    yield: '0.00',
    currentYield: '0.00',
    hectares: 0.0,
    compliance: 'Medium',
  },
]

export const cooperativeFarms = [
  {
    id: 'farm1',
    name: 'Baba Beji Farms',
    owner: 'Olamide Olutekunbi',
    ownerInitials: 'OO',
    ownerColor: '#F57C00',
    location: '21, Yusuf Aboki Street, Abapka GRA, Oke Ado',
    hectares: 0.0,
    region: 'Zango Kataf',
    lat: 9.9,
    lng: 8.3,
  },
  {
    id: 'farm2',
    name: 'BABA FARM',
    owner: 'Olamide Olutekunbi',
    ownerInitials: 'OO',
    ownerColor: '#F57C00',
    location: 'Zango Kataf',
    hectares: 0.0,
    region: 'Zango Kataf',
    lat: 10.1,
    lng: 8.0,
  },
  {
    id: 'farm3',
    name: 'Beta Agric Ventures',
    owner: 'Agrolinking Administrator',
    ownerInitials: 'AA',
    ownerColor: '#2E5A27',
    location: 'gjhjbdew',
    hectares: 5274.7,
    region: 'Local Govt Area',
    lat: 9.0765,
    lng: 7.3986,
  },
  {
    id: 'farm4',
    name: 'Daura Farms',
    owner: 'Agrolinking Administrator',
    ownerInitials: 'AA',
    ownerColor: '#2E5A27',
    location: 'Jibia, Katsina State, Nigeria',
    hectares: 100.9,
    region: 'Jibia',
    lat: 13.0833,
    lng: 7.2167,
  },
  {
    id: 'farm5',
    name: 'Daura Farms',
    owner: 'Agrolinking Administrator',
    ownerInitials: 'AA',
    ownerColor: '#2E5A27',
    location: 'Jibia, Katsina State, Nigeria',
    hectares: 100.5,
    region: 'Jibia',
    lat: 13.0833,
    lng: 7.2167,
  },
  {
    id: 'farm6',
    name: 'Expan Farms',
    owner: 'Olamide Olutekunbi',
    ownerInitials: 'OO',
    ownerColor: '#F57C00',
    location: 'hgahdkl',
    hectares: 2963.5,
    region: 'Garki',
    lat: 9.0,
    lng: 7.4,
  },
  {
    id: 'farm7',
    name: 'Hense Farm',
    owner: 'Agrolinking Administrator',
    ownerInitials: 'AA',
    ownerColor: '#2E5A27',
    location: 'sfdsgfhg,mc',
    hectares: 7268.7,
    region: 'Sokoto',
    lat: 13.0,
    lng: 5.2,
  },
  {
    id: 'farm8',
    name: 'IITA FCI4Afric Farm',
    owner: 'Agrolinking Administrator',
    ownerInitials: 'AA',
    ownerColor: '#2E5A27',
    location: 'IITA Nigeria Office',
    hectares: 1833.5,
    region: 'Ibadan',
    lat: 7.3,
    lng: 3.8,
  },
  {
    id: 'farm9',
    name: 'Jenny Farms and Co',
    owner: 'Agrolinking Administrator',
    ownerInitials: 'AA',
    ownerColor: '#2E5A27',
    location: 'Bagary Coconut Area',
    hectares: 0.0,
    region: 'Lagos',
    lat: 6.5,
    lng: 3.3,
  },
  {
    id: 'farm10',
    name: 'Ola',
    owner: 'Olamide Olutekunbi',
    ownerInitials: 'OO',
    ownerColor: '#F57C00',
    location: 'UYeruhrwuwair',
    hectares: 0.1,
    region: 'Zango Kataf',
    lat: 9.9,
    lng: 8.3,
  },
  {
    id: 'farm11',
    name: 'Olamide & Co farms',
    owner: 'Olamide Olutekunbi',
    ownerInitials: 'OO',
    ownerColor: '#F57C00',
    location: 'Lagos express way',
    hectares: 0.0,
    region: 'Lagos',
    lat: 6.5,
    lng: 3.3,
  },
  {
    id: 'farm12',
    name: 'Olamide Farm',
    owner: 'Olamide Olutekunbi',
    ownerInitials: 'OO',
    ownerColor: '#F57C00',
    location: 'Kakuri Textile Company',
    hectares: 0.0,
    region: 'Kaduna',
    lat: 10.5,
    lng: 7.4,
  },
]

export const cooperativeFarmers = [
  {
    id: 'f1',
    name: 'Me sef',
    identifier: 'adasd, MDs',
    phone: '+2348232313123',
    avatar: '/avatars/1.png',
  },
  {
    id: 'f2',
    name: 'Olamide Olutekunbi',
    identifier: '',
    phone: '',
    avatar: '/avatars/2.png',
  },
]

export const quickActions = [
  {
    id: 'tasks',
    label: 'Receive Harvest Batch',
    icon: 'package',
    href: '/cooperative/operations/record',
  },
  {
    id: 'record',
    label: 'Record Operation',
    icon: 'clipboard-list',
    href: '/cooperative/operations/record',
  },
  {
    id: 'qa',
    label: 'QA / QC Test',
    icon: 'test-tube',
    href: '/cooperative/operations/record',
  },
]

export const mapFarms = [
  {
    id: '1',
    name: 'Baba Beji Farms',
    location: 'Oke Ado',
    region: 'Zango Kataf',
    hectares: 0.0,
    lat: 9.9,
    lng: 8.3,
  },
  {
    id: '2',
    name: 'BABA FARM',
    location: 'Zango Kataf',
    region: 'Zango Kataf',
    hectares: 0.0,
    lat: 10.1,
    lng: 8.0,
  },
  {
    id: '3',
    name: 'Expan Farms',
    location: 'Local Area',
    region: 'Garki',
    hectares: 2963.5,
    lat: 9.0,
    lng: 7.4,
  },
  {
    id: '4',
    name: 'Hense Farm',
    location: 'Sokoto City',
    region: 'Sokoto',
    hectares: 7268.7,
    lat: 13.0,
    lng: 5.2,
  },
  {
    id: '5',
    name: 'IITA FCI4Afric Farm',
    location: 'Ibadan',
    region: 'Ibadan',
    hectares: 1833.5,
    lat: 7.3,
    lng: 3.8,
  },
  {
    id: '6',
    name: 'Beta Agric Ventures',
    location: 'Unknown',
    region: 'Lagos',
    hectares: 5274.7,
    lat: 6.5,
    lng: 3.3,
  },
  {
    id: '7',
    name: 'Daura Farms',
    location: 'Jibia',
    region: 'Jibia',
    hectares: 100.9,
    lat: 13.0,
    lng: 7.2,
  },
]

export const recentPurchases = [
  {
    date: 'Jan 07, 2026',
    farmer: 'Olamide Olutekunbi',
    farm: 'Baba Beji Farms',
    beneficiary: 'Olamide Olutekunbi',
    account: 'Cash',
    amount: '₦5,000',
  },
]

export const recentReceivables = [
  {
    date: 'Jan 07, 2026',
    farmer: 'Olamide Olutekunbi',
    farm: 'Baba Beji Farms',
    product: 'Sesame (BATCH-1759875835858)',
    quantity: '200',
    amount: '₦5,000',
  },
  {
    date: 'Jan 07, 2026',
    farmer: 'Olamide Olutekunbi',
    farm: 'Baba Beji Farms',
    product: 'Sesame (BATCH-1759875835858)',
    quantity: '20',
    amount: '₦5,000',
  },
]

export const cooperativeCertifications = [
  {
    id: '1',
    name: 'global_gap',
    subtitle: 'w',
    certificateNo: 'CERT-1771686980745',
    issueDate: 'Feb 11, 2026',
    expiryDate: 'Feb 24, 2026',
    appliedTo: 'Olamide Farms',
    appliedToLabel: 'Olamide Farms',
    status: 'active',
    verification: 'Unverified',
    type: 'farm',
  },
  {
    id: '2',
    name: 'rainforest',
    subtitle: 'sdsd',
    certificateNo: 'CERT-1771687141408',
    issueDate: 'Feb 20, 2026',
    expiryDate: 'Feb 25, 2026',
    appliedTo: 'Maize',
    appliedToLabel: 'Maize',
    status: 'active',
    verification: 'Unverified',
    type: 'product',
  },
]

export const complianceOverview = [
  {
    id: '1',
    product: 'Maize',
    productId: 'BATCH-8022dd4d-1770974808765',
    category: 'Agricultural Product',
    origin: 'N/A',
    riskLevel: 'Medium',
    complianceScore: 0,
    certifications: 0,
    alerts: 0,
    lastAudit: 'Never',
  },
]

// ─── Crop Cycles ──────────────────────────────────────────────────

export interface CropCycle {
  id: string
  productName: string
  variety: string
  farmId: string
  farmName: string
  farmLocation: string
  farmer: string
  farmerInitials: string
  farmerColor: string
  status: 'planning' | 'completed'
  plantedDate: string
  expectedHarvest: string
  area: number | string
  season: string
  daysToHarvest?: number
}

/** All crop cycles (for the Record Operation listing page) */
export const allCropCycles: CropCycle[] = [
  {
    id: 'cc-20',
    productName: 'Ginger',
    variety: 'mmmf',
    farmId: '1',
    farmName: 'Baba Beji Farms',
    farmLocation: 'Location not specified',
    farmer: 'Olamide Olutekunbi',
    farmerInitials: 'OO',
    farmerColor: '#F57C00',
    status: 'planning',
    plantedDate: '3/5/2026',
    expectedHarvest: '',
    area: '0.00956288156998043',
    season: '',
    daysToHarvest: 26,
  },
  {
    id: 'cc-21',
    productName: 'Cassava',
    variety: '419',
    farmId: '10',
    farmName: 'Titilayo Farm',
    farmLocation: 'Location not specified',
    farmer: 'Agrolinking Administrator',
    farmerInitials: 'AA',
    farmerColor: '#264d10',
    status: 'planning',
    plantedDate: '3/2/2026',
    expectedHarvest: '',
    area: 123.67,
    season: '',
    daysToHarvest: 301,
  },
  {
    id: 'cc-10',
    productName: 'Maize',
    variety: 'Yellow Maize',
    farmId: '8',
    farmName: 'Jenny Farms and Co',
    farmLocation: 'Location not specified',
    farmer: 'Agrolinking Administrator',
    farmerInitials: 'AA',
    farmerColor: '#264d10',
    status: 'planning',
    plantedDate: '2/20/2026',
    expectedHarvest: '',
    area: '',
    season: '',
    daysToHarvest: 7,
  },
  {
    id: 'cc-11',
    productName: 'Maize',
    variety: 'ascv',
    farmId: '13',
    farmName: "Shard's Farm",
    farmLocation: 'Location not specified',
    farmer: 'Agrolinking Administrator',
    farmerInitials: 'AA',
    farmerColor: '#264d10',
    status: 'planning',
    plantedDate: '',
    expectedHarvest: '',
    area: '',
    season: '',
    daysToHarvest: 6,
  },
  {
    id: 'cc-12',
    productName: 'Bean',
    variety: 'Brown Beans',
    farmId: '7',
    farmName: 'IITA FCI4Afric Farm',
    farmLocation: 'Location not specified',
    farmer: 'Agrolinking Administrator',
    farmerInitials: 'AA',
    farmerColor: '#264d10',
    status: 'planning',
    plantedDate: '2/13/2026',
    expectedHarvest: '',
    area: 78.09,
    season: '',
    daysToHarvest: 147,
  },
  {
    id: 'cc-13',
    productName: 'Maize',
    variety: 'Vitamin A',
    farmId: '7',
    farmName: 'IITA FCI4Afric Farm',
    farmLocation: 'Location not specified',
    farmer: 'Agrolinking Administrator',
    farmerInitials: 'AA',
    farmerColor: '#264d10',
    status: 'completed',
    plantedDate: '',
    expectedHarvest: '',
    area: '',
    season: '',
  },
  {
    id: 'cc-14',
    productName: 'Tomatoes',
    variety: 'varity a',
    farmId: '3',
    farmName: 'Beta Agric Ventures',
    farmLocation: 'Location not specified',
    farmer: 'Agrolinking Administrator',
    farmerInitials: 'AA',
    farmerColor: '#264d10',
    status: 'planning',
    plantedDate: '1/20/2026',
    expectedHarvest: '',
    area: 229.82,
    season: '',
    daysToHarvest: 33,
  },
  {
    id: 'cc-15',
    productName: 'Beans',
    variety: 'varity a',
    farmId: '6',
    farmName: 'Hense Farm',
    farmLocation: 'Location not specified',
    farmer: 'Agrolinking Administrator',
    farmerInitials: 'AA',
    farmerColor: '#264d10',
    status: 'planning',
    plantedDate: '1/12/2026',
    expectedHarvest: '',
    area: 304.89,
    season: '',
  },
]
