import type { ProductTransfer, TransferOffer } from '~/types/transfer'

export const mockTransfers: ProductTransfer[] = [
  {
    id: 't1',
    batchId: 'BATCH-1758814569861',
    productName: 'Cashew',
    farmerName: 'Deborah Ogunyemi Farm',
    farmName: 'Deborah Ogunyemi Farm',
    location: 'Zone 16, Kute, Iwo Road',
    quantity: 2000,
    unit: 'KG',
    status: 'available',
  },
  {
    id: 't2',
    batchId: 'BATCH-1758814569862',
    productName: 'Cashew',
    farmerName: 'Deborah Ogunyemi Farm',
    farmName: 'Deborah Ogunyemi Farm',
    location: 'Zone 16, Kute, Iwo Road',
    quantity: 2000,
    unit: 'KG',
    status: 'available',
  },
  {
    id: 't3',
    batchId: 'BATCH-1758814569863',
    productName: 'Cashew',
    farmerName: 'Deborah Ogunyemi Farm',
    farmName: 'Deborah Ogunyemi Farm',
    location: 'Zone 16, Kute, Iwo Road',
    quantity: 2000,
    unit: 'KG',
    status: 'ready_for_pickup',
  },
  {
    id: 't4',
    batchId: 'BATCH-1758814569864',
    productName: 'Cashew',
    farmerName: 'Deborah Ogunyemi Farm',
    farmName: 'Deborah Ogunyemi Farm',
    location: 'Zone 16, Kute, Iwo Road',
    quantity: 2000,
    unit: 'KG',
    status: 'ready_for_pickup',
  },
]

export const mockOffers: TransferOffer[] = [
  {
    id: 'o1',
    transporterName: 'O and Co Transport',
    location: 'Kaduna, Nigeria',
    phone: '+2348140928756',
    quantity: 20000,
    unit: 'kg',
    status: 'pending',
    avatar: 'https://i.pravatar.cc/150?u=o1',
  },
  {
    id: 'o2',
    transporterName: 'O and Co Transport',
    location: 'Kaduna, Nigeria',
    phone: '+2348140928756',
    quantity: 20000,
    unit: 'kg',
    status: 'pending',
    avatar: 'https://i.pravatar.cc/150?u=o2',
  },
  {
    id: 'o3',
    transporterName: 'O and Co Transport',
    location: 'Kaduna, Nigeria',
    phone: '+2348140928756',
    quantity: 20000,
    unit: 'kg',
    status: 'pending',
    avatar: 'https://i.pravatar.cc/150?u=o3',
  },
  {
    id: 'o4',
    transporterName: 'O and Co Transport',
    location: 'Kaduna, Nigeria',
    phone: '+2348140928756',
    quantity: 20000,
    unit: 'kg',
    status: 'pending',
    avatar: 'https://i.pravatar.cc/150?u=o4',
  },
]
